# Generated by Django 2.2.2 on 2019-06-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
