# Generated by Django 2.2.2 on 2019-06-28 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0004_cliente_servico_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereco_id',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='telefone',
            old_name='numero',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefones',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.Telefone'),
        ),
    ]
