# Generated by Django 2.2.2 on 2019-06-29 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0005_auto_20190628_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DINHEIRO', 'DINHEIRO'), ('CARTÂO', 'CARTÂO'), ('PRAZO', 'PRAZO')], max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('vendedor', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.Cliente')),
                ('produtos', models.ManyToManyField(to='oficina.Produto')),
                ('servicos', models.ManyToManyField(to='oficina.Servico')),
            ],
        ),
    ]
