# Generated by Django 2.2.2 on 2019-06-29 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0007_auto_20190628_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
