# Generated by Django 2.2.2 on 2019-06-30 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0009_fornecedor_telefones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefones',
        ),
        migrations.AddField(
            model_name='telefone',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficina.Fornecedor'),
        ),
    ]
