# Generated by Django 2.2.2 on 2019-06-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0010_auto_20190630_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_fabrica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('+', 'Positivo'), ('-', 'Negativo'), ('0', 'Nulo')], default='Nulo', max_length=1),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficina.Cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='oficina.Produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='servicos',
            field=models.ManyToManyField(blank=True, to='oficina.Servico'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficina.Categoria'),
        ),
    ]
