# Generated by Django 2.2.3 on 2019-07-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0011_auto_20190630_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.Telefone'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
