# Generated by Django 2.2.3 on 2019-07-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0012_auto_20190701_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='servicos',
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.Telefone'),
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('numero_item', models.IntegerField(editable=False, verbose_name='Nº do Item')),
                ('preco', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço')),
                ('item_cancelado', models.BooleanField(default=False, verbose_name='Item cancelado')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficina.Produto')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficina.Servico')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.Venda')),
            ],
        ),
    ]
