# Generated by Django 2.2.3 on 2019-07-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0014_auto_20190706_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='item_cancelado',
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficina.Venda'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficina.OrcamentoVenda'),
        ),
    ]
