# Generated by Django 2.2.3 on 2019-07-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0016_auto_20190708_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='preco',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
