# Generated by Django 2.2.3 on 2019-07-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0018_auto_20190708_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentovenda',
            name='status',
            field=models.BooleanField(),
        ),
    ]
