# Generated by Django 2.2.3 on 2019-07-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0021_auto_20190715_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['descricao']},
        ),
        migrations.AddField(
            model_name='orcamentovenda',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
