# Generated by Django 2.2.3 on 2019-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0022_auto_20190715_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
